### ISSUE TITLE
Can't trigger a build on Netlify

### ISSUE THREAD

**Issue by DaliborIlic** [gsumpster/grav-plugin-webhooks#1]
I need to make a POST request to https://api.netlify.com/build_hooks/xxxxxxxxxxxxxxxxxxxxxx (x's beeing the build number) after anything is published (created, edited, etc..).
I was excited when I saw your plugin, tried, but it doesn't seem to make that POST for me...
I'm not sure if it working with the latest GRAV (as I see the plugin is from 2016.) 
Thanks!

**Comment by gsumpster** [comment]
Hi!

Unfortunately, this is is an abandoned project of mine and doesn't work. 

Apologies for the inconvenience, I'll archive the project.
